version: "3.7"

services:
  exercise-two:
    container_name: exercise-two
    environment:
      - JWT_SECRET=JWT_SECRET
      - PORT=8000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
